In [3]:
import numpy as np

In [4]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [5]:
print("Week 1 Temperatures (°C):", temperatures_w1)

Week 1 Temperatures (°C): [22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [6]:
print("Shape:", temperatures_w1.shape)

Shape: (7,)

In [7]:
print("Data type:", temperatures_w1.dtype)

Data type: float64

In [8]:
print("Number of elements:", temperatures_w1.size)

Number of elements: 7

In [9]:
temperatures_w1_f = (temperatures_w1 * 9/5) + 32

In [10]:
print("Week 1 Temperatures (°F):", temperatures_w1_f)

Week 1 Temperatures (°F): [72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [11]:
print("Maximum temperature (°C):", np.max(temperatures_w1))

Maximum temperature (°C): 26.1

In [12]:
print("Minimum temperature (°C):", np.min(temperatures_w1))

Minimum temperature (°C): 20.8

In [13]:
print("Mean temperature (°C):", np.mean(temperatures_w1))

Mean temperature (°C): 23.542857142857144

In [14]:
first_three = temperatures_w1[:3]
print("First three days:", first_three)

First three days: [22.5 25.3 20.8]

In [15]:
weekend = temperatures_w1[-2:]
print("Weekend:", weekend)

Weekend: [24.8 21.9]

In [16]:
middle_three = temperatures_w1[2:5]
print("Middle three days:", middle_three)

Middle three days: [20.8 23.4 26.1]

In [17]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],   
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]    
])

In [18]:
print("2D Temperatures array:\n", temperatures)
print("Shape:", temperatures.shape)

2D Temperatures array:
 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]
Shape: (2, 7)

In [19]:
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

Data type: float64
Total number of elements: 14

In [20]:
week1 = temperatures[0]
week2 = temperatures[1]
print("Week 1:", week1)
print("Week 2:", week2)

Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]

In [21]:
weekend_both = temperatures[:, -2:]
print("Weekend (both weeks):\n", weekend_both)

Weekend (both weeks):
 [[24.8 21.9]
 [22.8 20.1]]

In [22]:
import pandas as pd

In [23]:
marks = pd.Series([95, 92, 89, 85, 80],
index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [24]:
print("1st rank mark:", marks.iloc[0])

1st rank mark: 95

In [25]:
print("Top 3 ranks:\n", marks.loc['Rank1':'Rank3'])

Top 3 ranks:
 Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [26]:
print("3rd rank mark:", marks.iloc[2])

3rd rank mark: 89

In [27]:
mask = marks > 90
print("Ranks with marks > 90:\n", marks[mask])
print("Rank labels only:", list(marks[mask].index))

Ranks with marks > 90:
 Rank1    95
Rank2    92
dtype: int64
Rank labels only: ['Rank1', 'Rank2']

In [28]:
marks['Rank1'] = 100
print("After modifying Rank1:\n", marks)

After modifying Rank1:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [29]:
marks = marks.drop('Rank5')
print("After removing Rank5:\n", marks)

After removing Rank5:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [30]:
cgpa = marks / 10
print("CGPA:\n", cgpa)

CGPA:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [31]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West',
               'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [32]:
print("DataFrame:\n", transactions)
print("\nHead:\n", transactions.head())
print("\nTail:\n", transactions.tail())
print("\nShape:", transactions.shape)
print("\nColumn names:", list(transactions.columns))
print("\nData types:\n", transactions.dtypes)
transactions.info()

DataFrame:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Head:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail:
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape: (10, 4)

Column names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']

Data types:
 TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [33]:
transactions[['ProductCategory', 'Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [34]:
print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [35]:
print(transactions.loc[:, ['ProductCategory', 'Region', 'Amount']])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [36]:
transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [37]:
print("Value counts:\n", transactions['ProductCategory'].value_counts())
print("\nUnique regions:", transactions['Region'].unique())

Value counts:
 ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

Unique regions: ['North' 'South' 'East' 'West']

In [38]:
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [39]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [40]:
transactions['Discount'] = transactions['Amount'] * 0.10
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [41]:
transactions = transactions[transactions['TransactionID'] != 109]
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [42]:
transactions = transactions.drop(columns='Discount')
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400